pipeline {
    agent any 
    stages {
        stage('checkout from git') {
            steps {
                git branch: 'master',
                    credentialsId: 'ssh-key',
                    url: 'ssh://192.168.178.30/volume1/git_repos/homeautomation.git'
            }
        }
        stage('build image') {
            steps {
                dir ('mqtt-elasticsearch-bridge') {
                    sh 'ls -la'
                }
            }
        }
    }
}