pipeline {
    agent any 
    stages {
        stage('checkout from git') {
            steps {
                git branch: 'master',
                    credentialsId: 'ssh-key',
                    url: 'ssh://192.168.178.30/volume1/git_repos/homeautomation.git'
            }
        }
        stage('build docker image') {
            steps {
                dir ('mqtt-elasticsearch-bridge') {
                    sh 'sudo docker build .'
                }
            }
        }
        stage('run docker image') {
            steps {
                docker.withServer('tcp://192.168.178.30:2375') {
                    def testImage = docker.build("python-test")
                    testImage.inside {
                        sh 'ls -la'
                    }
                }
            }
        }        
    }
}